version: "3.9"

services:
  ogpserver:
    image: node:19
    container_name: ogpserver
    command: node /home/code/server/
    volumes:
      - ./:/home/code/
      - ./dist:/dist
    networks:
      - frontend-network
      - api-network
    ports:
      - 3001:3001

  frontend:
    container_name: frontend
    build:
      context: "."
    command: npm run dev
    volumes:
      - ./:/home/code/
    ports:
      - 8000:8000
    networks:
      - frontend-network
      - api-network
    environment:
      CHOKIDAR_USEPOLLING: 1

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/front.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-network
      - frontend-network
      - nginx-network
    ports:
      - 80:80

networks:
  api-network:
    name: api_network
    external: true
  nginx-network:
    name: nginx_network
    driver: bridge
  frontend-network:
    driver: bridge
