version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: "."
    command: make compile-serve
    volumes:
      - ./:/home/code/
    ports:
      - 8000:8000
    networks:
      - frontend-network
      - api-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./config/front.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-network
      - frontend-network
    depends_on:
      - frontend
    ports:
      - 80:80

networks:
  api-network:
    name: api_network
    external: true
  frontend-network:
    driver: bridge
