version: "3.9"

services:
  mock:
    build: "."
    command: node mock/index.js
    volumes:
      - ./mock/:/home/code/mock
      - ./package.json:/home/code/package.json
      - ./node_modules/:/home/code/node_modules/
    ports:
      - 8080:8080
    network_mode: host

  frontend:
    build: "."
    command: npm run server
    volumes:
      - ./:/home/code/
    ports:
      - 8000:8000
    network_mode: host

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./mock/mock.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
    depends_on:
      - mock
      - frontend

