FROM node:19 AS base

WORKDIR /home/code/

RUN adduser node sudo

COPY *.json /home/code/

RUN npm install

COPY public /home/code/public
COPY webpack.config.cjs .

RUN npm run build

FROM nginx

WORKDIR /app/

COPY --from=base /home/code/dist /app/
COPY prod/nginx.conf /etc/nginx/conf.d/default.conf
COPY prod/index.html /app/

CMD ["nginx", "-g", "daemon off;"]
