version: "3.9"

services:
  ogpserver:
    image: node:19
    container_name: ogpserver
    command: node /home/code/server/
    volumes:
      - ./:/home/code/
      - ./prod:/dist
    networks:
      - frontend-network
      - api-network

  nginx:
    container_name: nginx
    build:
      dockerfile: "prod/Dockerfile.prod"
      context: "."
    volumes:
      - ./:/home/code/
    networks:
      - frontend-network
      - nginx-network
      - api-network
    depends_on:
      - ogpserver
    ports:
      - "81:80"

networks:
  api-network:
    name: api_network
    external: true
  nginx-network:
    name: nginx_network
    driver: bridge
  frontend-network:
    driver: bridge
