FROM node:19 AS base

WORKDIR /home/code/

RUN adduser node sudo

COPY *.json /home/code/
COPY public /home/code/public
COPY server /home/code/server

RUN npm install --omit=dev
RUN npm run compile

EXPOSE 8000

CMD [ "npm", "run", "server" ]
