name: Frontend

on:
    push:

jobs:
    linting:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [19.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Restoring npm cache
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Bootstraping packages
              if: steps.npm-cache.outputs.cache-hit != 'true'
              run: npm install

            - name: ESLint Checking
              run: npm run lint

            - name: TSLint Checking
              run: npx tsc --noEmit

            - name: Run jest
              run: npm run test
            
            - name: Run parcel build
              run: npm run build
